import builtins
import asyncio
import sys
from types import SimpleNamespace

import pytest

from k_search.kernel_generators.llm_clients import (
    ClaudeAgentLLMClient,
    OpenAICompatibleLLMClient,
    build_llm_client,
    normalize_llm_provider,
)


class _FakeResponses:
    def __init__(self):
        self.calls = []

    def create(self, **kwargs):
        self.calls.append(kwargs)
        return SimpleNamespace(output_text="responses text")


class _FakeChatCompletions:
    def __init__(self):
        self.calls = []

    def create(self, **kwargs):
        self.calls.append(kwargs)
        return SimpleNamespace(
            choices=[SimpleNamespace(message=SimpleNamespace(content="chat text"))]
        )


class _FakeOpenAIClient:
    def __init__(self, **kwargs):
        self.kwargs = kwargs
        self.responses = _FakeResponses()
        self.chat = SimpleNamespace(completions=_FakeChatCompletions())


class _FakeOpenAIModule:
    def __init__(self):
        self.instances = []

    def OpenAI(self, **kwargs):
        client = _FakeOpenAIClient(**kwargs)
        self.instances.append(client)
        return client


def _install_fake_claude_sdk(monkeypatch, query_func):
    fake_module = SimpleNamespace(
        ClaudeAgentOptions=lambda **kwargs: SimpleNamespace(kwargs=kwargs),
        query=query_func,
    )
    monkeypatch.setitem(sys.modules, "claude_agent_sdk", fake_module)
    return fake_module


def test_normalize_llm_provider_accepts_aliases():
    assert normalize_llm_provider(None) == "openai"
    assert normalize_llm_provider("openai") == "openai"
    assert normalize_llm_provider("openai-compatible") == "openai"
    assert normalize_llm_provider("claude_agent") == "claude-agent"
    assert normalize_llm_provider("claude") == "claude-agent"


def test_normalize_llm_provider_rejects_unknown_provider():
    with pytest.raises(ValueError, match="Unsupported LLM provider"):
        normalize_llm_provider("local-model")


def test_build_llm_client_defaults_to_openai(monkeypatch):
    fake_openai = _FakeOpenAIModule()
    monkeypatch.setitem(sys.modules, "openai", fake_openai)

    client = build_llm_client(
        llm_provider=None,
        model_name="gpt-5.2",
        api_key="key",
        base_url="https://api.example/v1",
        reasoning_effort="high",
    )

    assert isinstance(client, OpenAICompatibleLLMClient)
    assert fake_openai.instances[0].kwargs == {
        "api_key": "key",
        "base_url": "https://api.example/v1",
    }


def test_openai_reasoning_model_uses_responses_api():
    fake_openai = _FakeOpenAIModule()
    client = OpenAICompatibleLLMClient(
        model_name="gpt-5.2",
        api_key="key",
        base_url=None,
        reasoning_effort="high",
        openai_module=fake_openai,
    )

    assert client.generate("prompt") == "responses text"

    instance = fake_openai.instances[0]
    assert instance.responses.calls == [
        {
            "model": "gpt-5.2",
            "input": "prompt",
            "reasoning": {"effort": "high"},
        }
    ]
    assert instance.chat.completions.calls == []


def test_openai_non_reasoning_model_uses_chat_completions_api():
    fake_openai = _FakeOpenAIModule()
    client = OpenAICompatibleLLMClient(
        model_name="gemini-3-pro-preview",
        api_key="key",
        base_url="https://generativelanguage.googleapis.com/v1beta/",
        openai_module=fake_openai,
    )

    assert client.generate("prompt") == "chat text"

    instance = fake_openai.instances[0]
    assert instance.responses.calls == []
    assert instance.chat.completions.calls == [
        {
            "model": "gemini-3-pro-preview",
            "messages": [{"role": "user", "content": "prompt"}],
        }
    ]


def test_openai_provider_requires_api_key(monkeypatch):
    monkeypatch.delenv("LLM_API_KEY", raising=False)

    with pytest.raises(ValueError, match="LLM_API_KEY"):
        OpenAICompatibleLLMClient(model_name="gpt-5.2")


def test_build_llm_client_can_create_claude_agent_client(monkeypatch):
    async def fake_query(prompt, options):
        yield SimpleNamespace(result="generated by claude")

    _install_fake_claude_sdk(monkeypatch, fake_query)

    client = build_llm_client(
        llm_provider="claude-agent",
        model_name="claude-sonnet-4-6",
        api_key=None,
        base_url=None,
    )

    assert isinstance(client, ClaudeAgentLLMClient)
    assert client.generate("prompt") == "generated by claude"


def test_claude_agent_client_passes_model_and_disables_tools(monkeypatch):
    seen = {}

    async def fake_query(prompt, options):
        seen["prompt"] = prompt
        seen["options"] = options
        yield SimpleNamespace(result="claude text")

    _install_fake_claude_sdk(monkeypatch, fake_query)
    client = ClaudeAgentLLMClient(model_name="claude-sonnet-4-6")

    assert client.generate("hello") == "claude text"
    assert seen["prompt"] == "hello"
    assert seen["options"].kwargs["model"] == "claude-sonnet-4-6"
    assert seen["options"].kwargs["allowed_tools"] == []


def test_claude_agent_client_extracts_assistant_content_when_result_is_absent(monkeypatch):
    async def fake_query(prompt, options):
        yield SimpleNamespace(
            content=[
                SimpleNamespace(text="part one"),
                {"type": "text", "text": "part two"},
            ]
        )

    _install_fake_claude_sdk(monkeypatch, fake_query)
    client = ClaudeAgentLLMClient(model_name="claude-sonnet-4-6")

    assert client.generate("prompt") == "part one\npart two"


def test_claude_agent_client_rejects_error_result_message(monkeypatch):
    async def fake_query(prompt, options):
        yield SimpleNamespace(
            is_error=True,
            subtype="error_during_execution",
            result="failed but textual",
        )

    _install_fake_claude_sdk(monkeypatch, fake_query)
    client = ClaudeAgentLLMClient(model_name="claude-sonnet-4-6")

    with pytest.raises(
        RuntimeError,
        match="Claude Agent SDK.*error_during_execution.*failed but textual",
    ):
        client.generate("prompt")


def test_claude_agent_client_rejects_empty_text(monkeypatch):
    async def fake_query(prompt, options):
        yield SimpleNamespace(result="   ")

    _install_fake_claude_sdk(monkeypatch, fake_query)
    client = ClaudeAgentLLMClient(model_name="claude-sonnet-4-6")

    with pytest.raises(RuntimeError, match="Claude Agent SDK returned empty text"):
        client.generate("prompt")


def test_claude_agent_timeout_defaults_from_api_timeout_ms(monkeypatch):
    monkeypatch.delenv("KSEARCH_LLM_TIMEOUT_SECONDS", raising=False)
    monkeypatch.delenv("CLAUDE_AGENT_TIMEOUT_SECONDS", raising=False)
    monkeypatch.setenv("API_TIMEOUT_MS", "123000")

    client = ClaudeAgentLLMClient(model_name="claude-sonnet-4-6")

    assert client.timeout_seconds == 123.0


def test_claude_agent_timeout_reports_clear_error_when_sdk_child_is_cancelled(monkeypatch):
    async def fake_query(prompt, options):
        try:
            await asyncio.sleep(60)
        except asyncio.CancelledError:
            raise RuntimeError("Command failed with exit code 143") from None
        yield SimpleNamespace(result="unreachable")

    _install_fake_claude_sdk(monkeypatch, fake_query)
    client = ClaudeAgentLLMClient(model_name="claude-sonnet-4-6", timeout_seconds=0.01)

    with pytest.raises(TimeoutError, match="timed out after 0.01s"):
        client.generate("prompt")


def test_claude_agent_client_reports_missing_sdk(monkeypatch):
    real_import = builtins.__import__

    def fake_import(name, *args, **kwargs):
        if name == "claude_agent_sdk":
            raise ImportError("missing claude sdk")
        return real_import(name, *args, **kwargs)

    monkeypatch.setattr(builtins, "__import__", fake_import)

    client = ClaudeAgentLLMClient(model_name="claude-sonnet-4-6")

    with pytest.raises(RuntimeError, match="pip install claude-agent-sdk"):
        client.generate("prompt")


def test_kernel_generator_uses_injected_llm_client_for_prompt_generation():
    from k_search.kernel_generators.kernel_generator import KernelGenerator

    class FakeLLMClient:
        def __init__(self):
            self.prompts = []

        def generate(self, prompt):
            self.prompts.append(prompt)
            return "```python\nprint('hello')\n```"

    fake_client = FakeLLMClient()
    generator = KernelGenerator(
        model_name="fake-model",
        language="python",
        target_gpu="H100",
        api_key=None,
        llm_client=fake_client,
    )

    result = generator._generate_code_from_prompt("make code")

    assert fake_client.prompts == ["make code"]
    assert result["raw"] == "```python\nprint('hello')\n```"
    assert result["cleaned"] == "print('hello')"


def test_kernel_generator_strips_plain_text_from_injected_llm_client():
    from k_search.kernel_generators.kernel_generator import KernelGenerator

    class FakeLLMClient:
        def __init__(self):
            self.prompts = []

        def generate(self, prompt):
            self.prompts.append(prompt)
            return "  print('hello')  "

    fake_client = FakeLLMClient()
    generator = KernelGenerator(
        model_name="fake-model",
        language="python",
        target_gpu="H100",
        api_key=None,
        llm_client=fake_client,
    )

    result = generator._generate_code_from_prompt("make code")

    assert fake_client.prompts == ["make code"]
    assert result["raw"] == "print('hello')"
    assert result["cleaned"] == "print('hello')"


def test_world_model_generator_routes_llm_calls_through_injected_client():
    from k_search.kernel_generators.kernel_generator_world_model import (
        WorldModelKernelGeneratorWithBaseline,
    )

    class FakeLLMClient:
        def __init__(self):
            self.prompts = []

        def generate(self, prompt):
            self.prompts.append(prompt)
            return "wm text"

    fake_client = FakeLLMClient()
    generator = WorldModelKernelGeneratorWithBaseline(
        model_name="fake-model",
        language="python",
        target_gpu="H100",
        api_key=None,
        llm_client=fake_client,
    )

    assert generator._wm._llm_call("wm prompt") == "wm text"
    assert fake_client.prompts == ["wm prompt"]


def test_world_model_ascendc_root_action_prompt_uses_task_baseline():
    from k_search.kernel_generators.kernel_generator_world_model import (
        WorldModelKernelGeneratorWithBaseline,
    )

    class StopAfterPrompt(Exception):
        pass

    class FakeTask:
        name = "mqa"

        def get_definition_text(self, language):
            return "spec"

        def get_baseline_targets_text(self):
            return ""

        def get_code_format_text(self, language, target_gpu):
            return "<ascendc_patch>"

        def get_baseline_code_for_codegen(self, language):
            return "<ascendc_project>BASELINE_CODE</ascendc_project>"

        def code_for_world_model_from_raw(self, raw, language):
            return str(raw or "")

    class FakeWorldModel:
        def propose_action_nodes(self, **kwargs):
            return None

        def get_tree_path_text(self, definition_name):
            return ""

        def get(self, definition_name):
            return ""

        def choose_next_action_node_id(self, definition_name):
            return "n1"

        def set_active_leaf_id(self, definition_name, node_id):
            return None

        def get_node_obj(self, definition_name, node_id):
            return {
                "id": "n1",
                "node_id": "n1",
                "parent_id": "root",
                "action": {
                    "title": "optimize",
                    "difficulty_1_to_5": 1,
                    "expected_vs_baseline_factor": 1.1,
                },
            }

    captured = {}

    class FakeLLMClient:
        def generate(self, prompt):
            return ""

    generator = WorldModelKernelGeneratorWithBaseline(
        model_name="fake-model",
        language="ascendc",
        target_gpu="Ascend910B3",
        api_key=None,
        llm_client=FakeLLMClient(),
    )
    generator._wm = FakeWorldModel()
    generator._solution_db = None

    def capture_prompt(prompt, task):
        captured["prompt"] = prompt
        raise StopAfterPrompt

    generator._generate_code_from_prompt = capture_prompt

    with pytest.raises(StopAfterPrompt):
        generator._generate_world_model_cycles_v2(
            task=FakeTask(),
            max_opt_rounds=1,
            wm_stagnation_window=1,
            max_dai=1,
        )

    assert "BASELINE_CODE" in captured["prompt"]
    assert "(no base code; start from spec)" not in captured["prompt"]


def test_world_model_codegen_failure_marks_action_too_hard_and_returns_last_solution():
    from k_search.kernel_generators.kernel_generator_world_model import (
        WorldModelKernelGeneratorWithBaseline,
    )
    from k_search.tasks.task_base import EvalResult

    class FakeTask:
        name = "mqa"

        def get_definition_text(self, language):
            return "spec"

        def get_baseline_targets_text(self):
            return ""

        def get_code_format_text(self, language, target_gpu):
            return "<ascendc_patch>"

        def get_baseline_code_for_codegen(self, language):
            return "<ascendc_project>BASELINE_CODE</ascendc_project>"

        def code_for_world_model_from_raw(self, raw, language):
            return str(raw or "")

        def get_last_round_trace_logs_for_prompt(self):
            return "build failed"

        def run_benchmark(self, solution, dump_traces=False, round_num=0):
            return EvalResult(status="failed", log_excerpt="build failed")

    class FakeWorldModel:
        def __init__(self):
            self.too_hard_calls = []

        def propose_action_nodes(self, **kwargs):
            return None

        def get_tree_path_text(self, definition_name):
            return ""

        def get(self, definition_name):
            return ""

        def choose_next_action_node_id(self, definition_name):
            return "n1"

        def set_active_leaf_id(self, definition_name, node_id):
            return None

        def get_node_obj(self, definition_name, node_id):
            return {
                "id": "n1",
                "node_id": "n1",
                "parent_id": "root",
                "action": {
                    "title": "optimize",
                    "difficulty_1_to_5": 1,
                    "expected_vs_baseline_factor": 1.1,
                },
            }

        def get_solution_ref_for_node(self, definition_name, node_id):
            return None

        def note_action_too_hard(self, **kwargs):
            self.too_hard_calls.append(kwargs)

    class FakeLLMClient:
        def generate(self, prompt):
            return ""

    generator = WorldModelKernelGeneratorWithBaseline(
        model_name="fake-model",
        language="ascendc",
        target_gpu="Ascend910B3",
        api_key=None,
        llm_client=FakeLLMClient(),
    )
    fake_wm = FakeWorldModel()
    generator._wm = fake_wm
    generator._solution_db = None

    calls = {"count": 0}

    def generate_or_timeout(prompt, task):
        calls["count"] += 1
        if calls["count"] == 1:
            return {"raw": "candidate code", "cleaned": "candidate code"}
        raise TimeoutError("Claude Agent SDK provider timed out after 1200s")

    generator._generate_code_from_prompt = generate_or_timeout

    solution = generator._generate_world_model_cycles_v2(
        task=FakeTask(),
        max_opt_rounds=2,
        wm_stagnation_window=5,
        max_dai=5,
    )

    assert solution.name == "fake-model_mqa_ascendc_optimized_r1"
    assert len(fake_wm.too_hard_calls) == 1
    assert fake_wm.too_hard_calls[0]["eval_result"].status == "codegen_failed"


def test_world_model_debug_prompt_uses_applied_code_after_patch_response():
    from k_search.kernel_generators.kernel_generator_world_model import (
        WorldModelKernelGeneratorWithBaseline,
    )
    from k_search.tasks.task_base import EvalResult

    class StopAfterSecondPrompt(Exception):
        pass

    class FakeTask:
        name = "mqa"

        def get_definition_text(self, language, include_sources=True, include_format=True):
            return "spec"

        def get_baseline_targets_text(self):
            return ""

        def get_code_format_text(self, language, target_gpu):
            return "<ascendc_patch>"

        def get_baseline_code_for_codegen(self, language):
            return "<ascendc_project>BASELINE_CODE</ascendc_project>"

        def code_for_world_model_from_raw(self, raw, language):
            if raw == "RAW_PATCH_ONLY":
                return "<ascendc_project>APPLIED_FULL_CODE</ascendc_project>"
            return str(raw or "")

        def get_last_round_trace_logs_for_prompt(self):
            return "build failed"

        def run_benchmark(self, solution, dump_traces=False, round_num=0):
            return EvalResult(status="failed", log_excerpt="build failed")

    class FakeWorldModel:
        def propose_action_nodes(self, **kwargs):
            return None

        def get_tree_path_text(self, definition_name):
            return ""

        def get(self, definition_name):
            return ""

        def choose_next_action_node_id(self, definition_name):
            return "n1"

        def set_active_leaf_id(self, definition_name, node_id):
            return None

        def get_node_obj(self, definition_name, node_id):
            return {
                "id": "n1",
                "node_id": "n1",
                "parent_id": "root",
                "action": {
                    "title": "optimize",
                    "difficulty_1_to_5": 1,
                    "expected_vs_baseline_factor": 1.1,
                },
            }

        def get_solution_ref_for_node(self, definition_name, node_id):
            return None

    class FakeLLMClient:
        def generate(self, prompt):
            return ""

    generator = WorldModelKernelGeneratorWithBaseline(
        model_name="fake-model",
        language="ascendc",
        target_gpu="Ascend910B3",
        api_key=None,
        llm_client=FakeLLMClient(),
    )
    generator._wm = FakeWorldModel()
    generator._solution_db = None

    prompts = []

    def capture_second_prompt(prompt, task):
        prompts.append(prompt)
        if len(prompts) == 1:
            return {"raw": "RAW_PATCH_ONLY", "cleaned": "RAW_PATCH_ONLY"}
        raise StopAfterSecondPrompt

    generator._generate_code_from_prompt = capture_second_prompt

    with pytest.raises(StopAfterSecondPrompt):
        generator._generate_world_model_cycles_v2(
            task=FakeTask(),
            max_opt_rounds=2,
            wm_stagnation_window=5,
            max_dai=5,
        )

    assert len(prompts) == 2
    assert "APPLIED_FULL_CODE" in prompts[1]
    assert "RAW_PATCH_ONLY" not in prompts[1]
